export const translations = {
  en: {
    dashboard: "Dashboard",
    history: "History",
    settings: "Settings",
    systemStatus: "System Status",
    online: "Online",
    offline: "Offline",
    plantCondition: "Plant Condition",
    stressScore: "Stress Score",
    lastUpdate: "Last Update",
    healthy: "Healthy",
    stressed: "Stressed",
    earlyWarning: "Early Warning",
    critical: "Critical",
    acousticActivity: "Acoustic Activity",
    peakFrequency: "Peak Frequency",
    hour: "hr",
    statusMessageHealthy: "Monitoring continues. No issue detected.",
    statusMessageWarning: "Water stress detected.",
    statusMessageCritical: "ALARM: Critical dehydration, water immediately!",
    earlyWarningTitle: "Early Warning",
    criticalAlertTitle: "Critical Alert",
    irrigation: "Irrigation",
    lighting: "Lighting",
    ventilation: "Ventilation",
    readyToExecute: "Ready to Execute",
    soilMoisture: "Soil Moisture",
    temperature: "Temperature",
    leafColorAnalysis: "Leaf Color Analysis",
    calibrateSensor: "Calibrate Sensor",
    current: "Current",
    reference: "Reference",
    realTimeTrends: "Real-time Trends",
    dataHistory: "Data History",
    time: "Time",
    status: "Status",
    systemConfiguration: "System Configuration",
    espIpAddress: "ESP32 IP Address",
    pollingRate: "Polling Rate",
    interfaceTheme: "Interface Theme",
    interfaceLanguage: "Interface Language",
    saveChanges: "Save & Apply Changes",
    dark: "Dark",
    light: "Light",
    english: "English",
    turkish: "Turkish",
    russian: "Russian",
    developedBy: "Developed by",
    seconds: "Seconds",
    second: "Second",
    azerbaijani: "Azerbaijani",
    camera: "Camera",
    capture: "Capture",
    analyze: "Analyze",
    cameraAnalysis: "Camera Analysis",
    takePhoto: "Take Photo",
    resetCamera: "Reset Camera",
    cameraStatus: "Camera Status",
    cameraReady: "Camera Ready",
    cameraError: "Camera Error",
    selectCamera: "Select Camera",
    frontCamera: "Front Camera",
    backCamera: "Back Camera",
    defaultCamera: "Default Camera",
    notifications: "Notifications",
    enableNotifications: "Enable Notifications",
    notificationPermissionDenied: "Notification permission denied",
    lowMoistureAlert: "Low Soil Moisture Alert!",
    highStressAlert: "High Plant Stress Alert!",
    moistureLevelIs: "Moisture level is",
    stressLevelIs: "Stress level is",
    checkPlant: "Please check your plant.",
    notificationsEnabled: "Notifications Enabled",
    notificationsDisabled: "Notifications Disabled"
  },
  tr: {
    dashboard: "Panel",
    history: "Geçmiş",
    settings: "Ayarlar",
    systemStatus: "Sistem Durumu",
    online: "Çevrimiçi",
    offline: "Çevrimdışı",
    plantCondition: "Bitki Durumu",
    stressScore: "Stres Puanı",
    lastUpdate: "Son Güncelleme",
    healthy: "Sağlıklı",
    stressed: "Stresli",
    earlyWarning: "Erken Uyarı",
    critical: "Kritik",
    acousticActivity: "Akustik Aktivite",
    peakFrequency: "Pik Frekans",
    hour: "sa",
    statusMessageHealthy: "İzlemeye devam et. Sorun tespit edilmedi.",
    statusMessageWarning: "Su stresi tespit edildi.",
    statusMessageCritical: "ALARM: Kritik susuzluk, acil sula!",
    earlyWarningTitle: "Erken Uyarı",
    criticalAlertTitle: "Kritik Uyarı",
    irrigation: "Sulama",
    lighting: "Aydınlatma",
    ventilation: "Havalandırma",
    readyToExecute: "Yürütmeye Hazır",
    soilMoisture: "Toprak Nemi",
    temperature: "Sıcaklık",
    leafColorAnalysis: "Yaprak Rengi Analizi",
    calibrateSensor: "Sensörü Kalibre Et",
    current: "Güncel",
    reference: "Referans",
    realTimeTrends: "Gerçek Zamanlı Trendler",
    dataHistory: "Veri Geçmişi",
    time: "Zaman",
    status: "Durum",
    systemConfiguration: "Sistem Yapılandırması",
    espIpAddress: "ESP32 IP Adresi",
    pollingRate: "Sorgulama Hızı",
    interfaceTheme: "Arayüz Teması",
    interfaceLanguage: "Arayüz Dili",
    saveChanges: "Değişiklikleri Kaydet",
    dark: "Karanlık",
    light: "Aydınlık",
    english: "İngilizce",
    turkish: "Türkçe",
    russian: "Rusça",
    developedBy: "Geliştiren",
    seconds: "Saniye",
    second: "Saniye",
    azerbaijani: "Azerbaycan Türkçesi",
    camera: "Kamera",
    capture: "Çek",
    analyze: "Analiz Et",
    cameraAnalysis: "Kamera Analizi",
    takePhoto: "Fotoğraf Çek",
    resetCamera: "Kamerayı Sıfırla",
    cameraStatus: "Kamera Durumu",
    cameraReady: "Kamera Hazır",
    cameraError: "Kamera Hatası",
    selectCamera: "Kamera Seç",
    frontCamera: "Ön Kamera",
    backCamera: "Arka Kamera",
    defaultCamera: "Varsayılan Kamera",
    notifications: "Bildirimler",
    enableNotifications: "Bildirimleri Etkinleştir",
    notificationPermissionDenied: "Bildirim izni reddedildi",
    lowMoistureAlert: "Düşük Toprak Nemi Uyarısı!",
    highStressAlert: "Yüksek Bitki Stresi Uyarısı!",
    moistureLevelIs: "Nem seviyesi",
    stressLevelIs: "Stres seviyesi",
    checkPlant: "Lütfen bitkinizi kontrol edin.",
    notificationsEnabled: "Bildirimler Etkinleştirildi",
    notificationsDisabled: "Bildirimler Devre Dışı"
  },
  ru: {
    dashboard: "Панель",
    history: "История",
    settings: "Настройки",
    systemStatus: "Статус системы",
    online: "Онлайн",
    offline: "Офлайн",
    plantCondition: "Состояние растения",
    stressScore: "Уровень стресса",
    lastUpdate: "Последнее обновление",
    healthy: "Здоровое",
    stressed: "В состоянии стресса",
    earlyWarning: "Раннее предупреждение",
    critical: "Критическое",
    acousticActivity: "Акустическая активность",
    peakFrequency: "Пиковая частота",
    hour: "ч",
    statusMessageHealthy: "Мониторинг продолжается. Проблем не обнаружено.",
    statusMessageWarning: "Обнаружен водный стресс.",
    statusMessageCritical: "ТРЕВОГА: критическое обезвоживание, немедленно полейте!",
    earlyWarningTitle: "Раннее предупреждение",
    criticalAlertTitle: "Критическое предупреждение",
    irrigation: "Полив",
    lighting: "Освещение",
    ventilation: "Вентиляция",
    readyToExecute: "Готово к выполнению",
    soilMoisture: "Влажность почвы",
    temperature: "Температура",
    leafColorAnalysis: "Анализ цвета листьев",
    calibrateSensor: "Калибровка датчика",
    current: "Текущий",
    reference: "Эталон",
    realTimeTrends: "Режим реального времени",
    dataHistory: "История данных",
    time: "Время",
    status: "Статус",
    systemConfiguration: "Конфигурация системы",
    espIpAddress: "IP-адрес ESP32",
    pollingRate: "Частота опроса",
    interfaceTheme: "Тема интерфейса",
    interfaceLanguage: "Язык интерфейса",
    saveChanges: "Сохранить изменения",
    dark: "Темная",
    light: "Светлая",
    english: "Английский",
    turkish: "Турецкий",
    russian: "Русский",
    developedBy: "Разработано",
    seconds: "Секунд",
    second: "Секунда",
    azerbaijani: "Азербайджанский",
    camera: "Камера",
    capture: "Снять",
    analyze: "Анализировать",
    cameraAnalysis: "Анализ камеры",
    takePhoto: "Сделать фото",
    resetCamera: "Сбросить камеру",
    cameraStatus: "Статус камеры",
    cameraReady: "Камера готова",
    cameraError: "Ошибка камеры",
    selectCamera: "Выберите камеру",
    frontCamera: "Передняя камера",
    backCamera: "Задняя камера",
    defaultCamera: "Камера по умолчанию",
    notifications: "Уведомления",
    enableNotifications: "Включить уведомления",
    notificationPermissionDenied: "Доступ к уведомлениям отклонен",
    lowMoistureAlert: "Внимание! Низкая влажность почвы!",
    highStressAlert: "Внимание! Высокий уровень стресса растения!",
    moistureLevelIs: "Уровень стресса",
    stressLevelIs: "Уровень стресса",
    checkPlant: "Пожалуйста, проверьте состояние вашего растения.",
    notificationsEnabled: "Уведомления включены",
    notificationsDisabled: "Уведомления отключены"
  },
  az: {
    dashboard: "Panel",
    history: "Tarixçə",
    settings: "Ayarlar",
    systemStatus: "Sistem Statusu",
    online: "Onlayn",
    offline: "Oflayn",
    plantCondition: "Bitki Vəziyyəti",
    stressScore: "Stres Balı",
    lastUpdate: "Son Yeniləmə",
    healthy: "Sağlam",
    stressed: "Stresli",
    earlyWarning: "Erkən Xəbərdarlıq",
    critical: "Kritik",
    acousticActivity: "Akustik Fəaliyyət",
    peakFrequency: "Pik Tezlik",
    hour: "saat",
    statusMessageHealthy: "İzləmə davam edir. Problem aşkar edilmədi.",
    statusMessageWarning: "Su stresi aşkar edildi.",
    statusMessageCritical: "ALARM: Kritik susuzluq, təcili suvarın!",
    earlyWarningTitle: "Erkən Xəbərdarlıq",
    criticalAlertTitle: "Kritik Xəbərdarlıq",
    irrigation: "Suvarma",
    lighting: "İşıqlandırma",
    ventilation: "Havalandırma",
    readyToExecute: "İcra Etməyə Hazırdır",
    soilMoisture: "Torpaq Nəmi",
    temperature: "Temperatur",
    leafColorAnalysis: "Yarpaq Rəngi Analizi",
    calibrateSensor: "Sensoru Kalibrlə",
    current: "Cari",
    reference: "Referans",
    realTimeTrends: "Real Zamanlı Trendlər",
    dataHistory: "Məlumat Tarixçəsi",
    time: "Zaman",
    status: "Status",
    systemConfiguration: "Sistem Konfiqurasiyası",
    espIpAddress: "ESP32 IP Ünvanı",
    pollingRate: "Sorğu Tezliyi",
    interfaceTheme: "Arayüz Teması",
    interfaceLanguage: "Arayüz Dili",
    saveChanges: "Dəyişiklikləri Saxla",
    dark: "Qaranlıq",
    light: "Aydınlıq",
    english: "İngilis dili",
    turkish: "Türk dili",
    russian: "Rus dili",
    developedBy: "Hazırlayan",
    seconds: "Saniyə",
    second: "Saniyə",
    azerbaijani: "Azərbaycan dili",
    camera: "Kamera",
    capture: "Çək",
    analyze: "Analiz Et",
    cameraAnalysis: "Kamera Analizi",
    takePhoto: "Şəkil Çək",
    resetCamera: "Kameranı Sıfırla",
    cameraStatus: "Kamera Statusu",
    cameraReady: "Kamera Hazırdır",
    cameraError: "Kamera Xətası",
    selectCamera: "Kamera Seç",
    frontCamera: "Ön Kamera",
    backCamera: "Arxa Kamera",
    defaultCamera: "Varsayılan Kamera",
    notifications: "Bildirişlər",
    enableNotifications: "Bildirişləri Aktivləşdir",
    notificationPermissionDenied: "Bildiriş icazəsi rədd edildi",
    lowMoistureAlert: "Aşağı Torpaq Nəmi Xəbərdarlığı!",
    highStressAlert: "Yüksək Bitki Stresi Xəbərdarlığı!",
    moistureLevelIs: "Nəm səviyyəsi",
    stressLevelIs: "Stres səviyyəsi",
    checkPlant: "Zəhmət olmasa bitkinizi yoxlayın.",
    notificationsEnabled: "Bildirişlər Aktivləşdirildi",
    notificationsDisabled: "Bildirişlər Deaktiv Edildi"
  }
};
